accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('password', views.changepass_view, name="changepass"),
    path('myprofile', views.myprofile_view, name="myprofile"),
    path('login', views.login_view, name="login"),
    path('register', views.register_view, name="register"),
    path('logout', views.logout_view, name="logout"),
]

core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index_view, name="index"),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'MovieLibrary'
admin.site.site_title = 'MovieLibrary'

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('mylist/', include('mylist.urls')),
    path('browse/', include('movieseries.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieseries/urls.py
from django.urls import path
from . import views


app_name = 'movieseries'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<int:id>', views.detail_view, name='detail')
]

mylist/urls.py
from django.urls import path
from . import views

app_name = 'mylist'

urlpatterns = [
    path('', views.list_view, name="list")
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

movieseries/models.py
from django.db import models
from django.contrib.auth.models import User


class Comment(models.Model):

    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=255)

    def __str__(self):
        return "{0} | {1}".format(self.text, self.author)


class Player(models.Model):

    text = models.TextField(
        primary_key=True,
        unique=True,
        max_length=20
    )
    icon = models.ImageField(default='icons/default.png')


class Link(models.Model):

    id = models.AutoField(primary_key=True)
    link = models.TextField(unique=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return "{0} | {1}".format(self.id, self.player)


class Categories(models.Model):

    name = models.TextField(max_length=50, primary_key=True)

    def __str__(self):
        return self.name


class Movie(models.Model):

    id = models.AutoField(primary_key=True)
    title = models.TextField(max_length=200, verbose_name='Title')
    title_translated = models.TextField(
        max_length=200,
        blank=True,
        verbose_name='Translated Title'
    )
    director = models.TextField(
        max_length=150,
        blank=True,
        verbose_name='Director'
    )
    description = models.TextField(
        max_length=200,
        blank=True,
        verbose_name='Description'
    )
    added = models.DateField(auto_now_add=True, verbose_name='Added')
    movie_year = models.PositiveSmallIntegerField(
        blank=True,
        verbose_name='Year')
    cover = models.ImageField(
        upload_to='covers',
        blank=True,
        verbose_name='Cover',
        default="defaults/cover.png",
        max_length=200
    )
    categories = models.ManyToManyField(
        Categories,
        blank=True,
        verbose_name='Categories'
    )
    trailer_link = models.TextField(blank=True)
    link = models.ManyToManyField(Link, blank=True)
    comments = models.ManyToManyField(Comment, blank=True)

    def __str__(self):
        return "{0}. {1}({2}) by {3}".format(self.id, self.title, self.movie_year, self.director)

mylist/models.py
from django.db import models
from django.contrib.auth.models import User
from movieseries.models import Movie
# Create your models here.


class MyList(models.Model):

    id = models.AutoField(
        primary_key=True,
        default=1
    )
    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    show = models.ManyToManyField(
        Movie,
        blank=True,
        verbose_name='Movie'
    )
    # series

    def __str__(self):
        return str(self.user_id)

movieseries/forms.py
from django.forms import ModelForm
from . import models


class CreateComment(ModelForm):

    class Meta:

        model = models.Comment
        fields = ['text']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('core:index')
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {'form': form})


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('core:index')
    else:
        form = UserCreationForm()
    return render(request, "accounts/register.html", {'form': form})


@login_required
def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect('core:index')


@login_required
def myprofile_view(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user
    }
    return render(request, "accounts/myprofile.html", context)


@login_required
def changepass_view(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            redirect('accounts:myprofile')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/changepass.html', context)

core/views.py
from django.shortcuts import render
from movieseries.models import Movie

# Create your views here.


def index_view(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, "core/index.html", context)

movieseries/views.py
from django.shortcuts import render, Http404, redirect, get_object_or_404
from movieseries.models import Movie, Categories
from . import forms
# Create your views here.


def index_view(request):
    movies = Movie.objects.all()
    categories = Categories.objects.all()
    context = {
        'movies': movies,
        'categories': categories,
    }
    return render(request, 'movieseries/index.html', context)


def detail_view(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == 'POST':
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            instance.movie_set.add(movie)
            return redirect('movieseries:detail', id=id)
    else:
        form = forms.CreateComment()

    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movieseries/detail.html', context)

mylist/views.py
from django.shortcuts import render
from .models import MyList
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def list_view(request):
    mylist = MyList.objects.filter(user_id=request.user)
    context = {
        'list': mylist
    }
    return render(request, 'mylist/mylist.html', context)

templates/accounts/changepass.html
{% extends "base.html" %}
{% block content %}

<h1> Zmień hasło </h1>
<form method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit"> Zmień </button>
</form>

{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>Logowanie</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Zaloguj</button>
</form>
{% endblock content %}

templates/accounts/myprofile.html
{% extends "base.html" %}
{% load static from static %}
{% block imports %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock imports %}
{% block content %}
<h1>Ustawienia konta</h1>
<ul class="settings">
    <a href="{% url 'accounts:changepass' %}">
        <li>Zmień hasło</li>
    </a>
    <a href="#">
        <li>Zmień adres email</li>
    </a>
    <a href="#">
        <li>Usuń konto</li>
    </a>
</ul>

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %}
{% block content %}
<h1>Rejestracja</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zarejestruj</button>
</form>
{% endblock content %}

templates/base.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block imports %}
    {% endblock imports %}
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <title>MovieSeries</title>
</head>

<body>
    <header class="header">
        <nav class="navigation">
            <a href="{% url 'core:index' %}" class="logo">MovieSeries</a>
            <ul class="nav-left">
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'mylist:list'%}">Moja lista</a></li>
                {% endif %}
                <li class="nav-item"><a href="{% url 'movieseries:index' %}">Przegladaj</a></li>
            </ul>
            <ul class="nav-right">
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:myprofile' %}">Profil</a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}">Wyloguj</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'accounts:login' %}">Logowanie</a></li>
                <li class="nav-item"><a href="{% url 'accounts:register' %}">Zarejestruj się</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}

        {% endblock content %}
    </main>
    <footer>

    </footer>
</body>

</html>

templates/core/index.html
{% extends "base.html" %}
{% block content %}
<h1>Najlepsze</h1>
{% for movie in movies %}
<h1><a href="{% url 'movieseries:detail' id=movie.id %}">{{ movie.title }}</a></h1>
<img src="{{ movie.cover.url }}">
{% endfor %}
{% endblock content %}

templates/movieseries/detail.html
{% extends "base.html" %}
{% block content %}
{% if movie.title_translated %}
<h1> {{ movie.title_translated }}({{ movie.movie_year }}) / {{ movie.title }} </h1>
{% else %}
<h1> {{ movie.title }} ({{ movie.movie_year }}) </h1>
{% endif %}

<img src="{{ movie.cover.url }}">
<h2> Director: {{ movie.director }} </h2>
<h4> Description: {{ movie.description }} </h4>

<p>
    {% if user.is_authenticated %}
    <form action="{% url 'movieseries:detail' id=movie.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Comment</button>
    </form>
    {% endif %}
</p>

{% for comment in movie.comments.all %}
Author:{{comment.author}}
Text: {{comment.text}}
{% endfor %}
{% endblock content %}

templates/movieseries/index.html
{% extends "base.html" %}
{% load static from static %}

{% block imports %}
<link rel="stylesheet" href="{% static 'css/browse.css' %}">
{% endblock imports %}

{% block content %}
<h1>Przeglądaj</h1>
<div class="layout">
    <aside class="fillter">
        <div class="categories">
            <h2>Kategorie</h2>
            <ul>
                {% for category in categories %}
                <a href="#">
                    <li>{{ category.name }}</li>
                </a>
                {% endfor %}
            </ul>
        </div>
        <div class="myear">
            <h2>Rok produkcji</h2>
            <label> od: <input type="number" min="2000" max="2020" class="ypicker"> </label> </br>
            <label> do: <input type="number" min="2000" max="2020" class="ypicker"> </label>
        </div>
    </aside>
    <section class="movies">
        {% for movie in movies %}
        <div class="movie">
            <a href="{% url 'movieseries:detail' id=movie.id %}">
                <h2>{{ movie.title }} ({{ movie.movie_year }})</h2>
                <img src="{{ movie.cover.url }}">
            </a>
        </div>
        {% endfor %}
    </section>
</div>
{% endblock content %}

templates/mylist/mylist.html
{% extends "base.html" %}
{% load static from static %}
{% block imports%}
<link rel="stylesheet" href="{% static 'css/mylist.css' %}">
{% endblock imports %}

{% block content %}
<section class="list">
    <header class="block-head">
        <h1>Moja Lista</h1>
    </header>
    {% for movie in list %}
    <div class="list-element">
        <h2> {{movie.show.title }}</h2>
        <img src="{{ movie.show.cover.url }}">
    </div>
    {% endfor %}
</section>
{% endblock content %}